name: Merge Release Into Main

on:
  push:
    branches:
      - 'prod'

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: Get repository owner
        id: get_owner
        run: echo "::set-output name=owner::$(gh repo view --json owner --json-fields owner --repo $GITHUB_REPOSITORY)"

      - name: Extract owner username
        id: extract_owner
        run: echo "::set-output name=username::$(echo '${{ steps.get_owner.outputs.owner }}' | jq -r '.owner.login')"

      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: ${{ steps.extract_owner.outputs.username }}
          pr_assignee: ${{ steps.extract_owner.outputs.username }}

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: Enable automerge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge
